services:
  app:
    build:
        context: .
        dockerfile: docker/Dockerfile
    ports:
      - "8510:80"
    volumes:
      - .:/var/www/html
    networks:
      - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules
