services:
  app:
    build:
        context: .
        args:
          NEW_UID: ${NEW_UID:-1000}
          NEW_GID: ${NEW_GID:-1000}
    ports:
      - "8510:8510"
    volumes:
      - .:/app
    networks:
      - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules
